### ISSUE TITLE
[ERROR] config

### ISSUE THREAD

**Issue by Frodwo** [Arasple/TrHologram#29]
[19:02:12] [Server thread/INFO]: # --------------------------------------------- #
[19:02:12] [Server thread/INFO]: # HASH 70a8d5bdc0639110d8317767a758766d5e7ac868 #
[19:02:12] [Server thread/INFO]: # --------------------------------------------- #
[19:02:12] [Server thread/ERROR]: Cannot load source
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 93, column 18:
    Options: Language: zh_CN
                     ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.16.5.jar:git-Purpur-1079]
	at io.izzel.taboolib.module.db.local.SecuredFile.loadFromString(SecuredFile.java:62) ~[TabooLib.jar:?]
	at io.izzel.taboolib.module.db.local.SecuredFile.loadConfiguration(SecuredFile.java:95) ~[TabooLib.jar:?]
	at io.izzel.taboolib.module.config.TConfigMigrate.migrate(TConfigMigrate.java:41) ~[TabooLib.jar:?]
	at io.izzel.taboolib.module.config.TConfig.migrate(TConfig.java:163) ~[TabooLib.jar:?]
	at io.izzel.taboolib.module.inject.TInjectLoader.lambda$static$6(TInjectLoader.java:78) ~[TabooLib.jar:?]
	at io.izzel.taboolib.module.inject.TInjectLoader.inject(TInjectLoader.java:151) ~[TabooLib.jar:?]
	at io.izzel.taboolib.module.inject.TInjectLoader.lambda$postLoad$12(TInjectLoader.java:143) ~[TabooLib.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_291]
	at io.izzel.taboolib.module.inject.TInjectLoader.postLoad(TInjectLoader.java:142) ~[TabooLib.jar:?]
	at io.izzel.taboolib.TabooLibLoader.lambda$postLoadClass$8(TabooLibLoader.java:267) ~[TabooLib.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_291]
	at io.izzel.taboolib.TabooLibLoader.postLoadClass(TabooLibLoader.java:264) ~[TabooLib.jar:?]
	at io.izzel.taboolib.PluginLoader$1.onStarting(PluginLoader.java:65) ~[TabooLib.jar:?]
	at io.izzel.taboolib.PluginLoader.lambda$start$2(PluginLoader.java:195) ~[TabooLib.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_291]
	at io.izzel.taboolib.PluginLoader.start(PluginLoader.java:195) ~[TabooLib.jar:?]
	at me.arasple.mc.trhologram.module.internal.boot.PluginBoot.onEnable(PluginBoot.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1079]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Purpur-1079]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1079]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1070) ~[patched_1.16.5.jar:git-Purpur-1079]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1079]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 93, column 18:
    Options: Language: zh_CN
                     ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:869) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.16.5.jar:git-Purpur-1079]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.5.jar:git-Purpur-1079]
	... 27 more
[19:02:12] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-2 - Starting...
[19:02:12] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-2 - Start completed.
[19:02:12] [Server thread/INFO]: [TrHologram][INFO] 插件 TabooLib 註冊新的連接池: jdbc:sqlite:plugins\TabooLib\playerdata\v2\data.db
[19:02:12] [Server thread/WARN]: java.lang.Exception: No valid location
[19:02:12] [Server thread/WARN]: 	at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:77)
[19:02:12] [Server thread/WARN]: 	at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:68)
[19:02:12] [Server thread/WARN]: 	at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:59)
[19:02:12] [Server thread/WARN]: 	at me.arasple.mc.trhologram.TrHologram.onEnable(TrHologram.kt:31)
[19:02:12] [Server thread/WARN]: 	at me.arasple.mc.trhologram.module.internal.boot.PluginBoot.onEnable(PluginBoot.java:74)
[19:02:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:02:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[19:02:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[19:02:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[19:02:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[19:02:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593)
[19:02:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:293)
[19:02:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1070)
[19:02:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[19:02:12] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Arasple** [comment]
Reinstall your plugin
