### ISSUE TITLE
Error loading on Java 16

### ISSUE THREAD

**Issue by TUCAOEVER** [Arasple/TrHologram#30]
[14:05:10 WARN]: java.lang.NoSuchFieldException: ucp
[14:05:10 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[14:05:10 WARN]:        at me.arasple.mc.trhologram.module.internal.boot.util.ILoader.addPath(ILoader.java:65)
[14:05:10 WARN]:        at me.arasple.mc.trhologram.module.internal.boot.PluginBoot.init(PluginBoot.java:262)
[14:05:10 WARN]:        at me.arasple.mc.trhologram.module.internal.boot.PluginBoot.<clinit>(PluginBoot.java:287)
[14:05:10 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[14:05:10 WARN]:        at java.base/java.lang.Class.forName(Class.java:466)
[14:05:10 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82)
[14:05:10 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147)
[14:05:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:409)
[14:05:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:317)
[14:05:10 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393)
[14:05:10 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252)
[14:05:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066)
[14:05:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[14:05:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:05:10 WARN]: **** THE TABOOLIB COULD NOT BE LOADED ****
[14:05:10 WARN]: The TrHologram will be skipped loading, your environment is not supported.
[14:05:10 WARN]: If this warning should not appear here, please see http://github.com/TabooLib/TabooLib/issues for feedback.
[14:05:10 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[14:05:12 WARN]: Legacy plugin PlayerPoints v2.1.5-SNAPSHOT does not specify an api-version.
[14:05:12 WARN]: java.lang.NoSuchFieldException: ucp
[14:05:12 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[14:05:12 WARN]:        at me.arasple.mc.trmenu.module.internal.boot.util.ILoader.addPath(ILoader.java:65)
[14:05:12 WARN]:        at me.arasple.mc.trmenu.module.internal.boot.PluginBoot.init(PluginBoot.java:268)
[14:05:12 WARN]:        at me.arasple.mc.trmenu.module.internal.boot.PluginBoot.<clinit>(PluginBoot.java:293)
[14:05:12 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[14:05:12 WARN]:        at java.base/java.lang.Class.forName(Class.java:466)
[14:05:12 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82)
[14:05:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147)
[14:05:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:409)
[14:05:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:317)
[14:05:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393)
[14:05:12 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252)
[14:05:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066)
[14:05:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[14:05:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:05:12 WARN]: **** THE TABOOLIB COULD NOT BE LOADED ****
[14:05:12 WARN]: The TrMenu will be skipped loading, your environment is not supported.
[14:05:12 WARN]: If this warning should not appear here, please see http://github.com/TabooLib/TabooLib/issues for feedback.

**Comment by Arasple** [comment]
Fixed
Please download the latest actions build here https://github.com/Arasple/TrHologram/actions/runs/912113778

**Comment by msmanui** [comment]
> Fixed Please download the latest actions build here https://github.com/Arasple/TrHologram/actions/runs/912113778

Link has expired!
